version: '3.7'
services:
  app:
    image: 'node'
    command: bash -c 'npm install && npm run startTs'
    ports:
      - '3000:3000'
    working_dir: '/hostdir'
    volumes:
      - './:/hostdir'
    environment: 
      - MODE=dev
    depends_on: 
      - db
    networks:
      - coderitter
  db:
    image: 'mariadb'
    environment:
      - MYSQL_PASSWORD=1234
      - MARIADB_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=coderitter
      - MYSQL_USER=coderitter
    networks: 
      - coderitter
networks:
  coderitter:
    external: true