version: '3.7'
services:
  dbtest:
    image: 'mariadb'
    environment:
      - MYSQL_PASSWORD=1234
      - MARIADB_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=coderitter_test
      - MYSQL_USER=coderitter_test
    networks:
      - coderittertest
networks:
  coderittertest:
    external: true