version: '3.7'
services:
  app:
    image: 'node'
    command: bash -c 'npm install && npm run startTs'
    ports:
      - '3000:3000'
    working_dir: '/hostdir'
    volumes:
      - './:/hostdir'
    environment: 
      - MODE=dev
    networks:
      - coderitter
networks:
  coderitter:
    external: true