version: '3.7'
services:
  app:
    image: node
    restart: always
    working_dir: '/hostdir'
    volumes:
        - './:/hostdir'
    command: bash -c 'npm install && npm run build && npm start'
    environment: 
        - MODE=prod
networks:
  publicNet:
    external: true
