version: '3.7'
services:
  app:
    image: 'node'
    command: bash -c 'npm install && npm run startTs'
    ports:
      - '3000:3000'
    working_dir: '/hostdir'
    volumes:
      - './:/hostdir'
    environment: 
      - MODE=dev
    depends_on: 
      - db
    networks:
      - coderitter
  db:
    image: 'postgres'
    environment:
      - POSTGRES_DB=coderitter
      - POSTGRES_USER=coderitter
      - POSTGRES_PASSWORD=1234
    networks: 
      - coderitter
networks:
  coderitter:
    external: true