version: '3.7'
services:
  app:
    image: node
    restart: always
    working_dir: '/hostdir'
    volumes:
        - './:/hostdir'
    command: bash -c 'npm install && npm run build && npm start'
    environment: 
        - MODE=prod
    depends_on: 
        - db
  db:
    image: 'mariadb'
    environment:
      - MYSQL_PASSWORD=1234
      - MARIADB_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=coderitter_prod
      - MYSQL_USER=coderitter_prod
networks:
  publicNet:
    external: true
